### ISSUE TITLE
Can't load localhost anymore

### ISSUE THREAD

**Issue by djaiss** [rs/SafariOmnibar#1]
I have no idea why, but with this plugin on, I can't access to my localhost anymore. It redirects me to a google search which obviously is not useful, as I need it to run it locally :-)

**Comment by rs** [comment]
Hmm I see the issue. If you type http://localhost it should work. I'll fix this in a next revision.

**Comment by theunraveler** [comment]
For me, typing "http://localhost" doesn't work either.

**Comment by jgpippin** [comment]
I'm also unable to load it with http://localhost (or, in my instance, http://localhost:8888).  I would LOVE to see this fixed in the next revision, as this would fill my life with rainbows and unicorns.

**Comment by rs** [comment]
I'll fix this as soon as I come back from my holidays in two weeks.

**Comment by superwillyfoc** [comment]
I have the same error, :)
Congratulations for your great job, it works great and quickly!

**Comment by djmtype** [comment]
just need to emphasize port numbers don't work in general either, not just localhost.
e.g. http://mydomain:8888/

**Comment by da7id** [comment]
same problem here using MAMP with 8888, just takes me to a google search of "http://localhost:8888"

**Comment by jgpippin** [comment]
Just a thought to get you through until this issue is patched - you can bookmark localhost:8888 in your bookmarks toolbar (you'll have to create the bookmark and then edit the address).

Also, if you're an Alfred user and Safari is set to your default browser, you can enter the url in Alfred and it will load properly. Okay, swear I'll stop posting now.

**Comment by kurko** [comment]
While rs is on his holidays, type 127.0.0.1 instead of localhost :)

**Comment by stuffmc** [comment]
http://localhost:3000 not working is kind of a problem for a rails developer ;-)

**Comment by JeanMertz** [comment]
@stuffmc as a fellow Rails developer, here are better solutions to localhost:3000
1. **[Pow!](http://pow.mx/)** - _highly recommended rack server, easy to install, super easy to use (also see *_[powder](https://github.com/Rodreegez/powder)*\* to make it even easier), allows you to visit `mydomain.dev` or any other `.dev` domain*
2. `rails s -p 80` - _starts the server at port 80, allowing you to visit http://127.0.0.1/_
3. [smackaho.st:3000](http://smackaho.st:3000) - _routes to localhost:3000 (but you still have to use option 2 if including ports also redirects to google)_
4. [lvh.me:3000](http://lvh.me:3000) - _see option 3_

**Comment by stuffmc** [comment]
@JeanMertz Thanks. I know all this. Still, the plugin shouldn't search google for localhost:3000 so I'm not using it until it's fixed.

**Comment by jgpippin** [comment]
@JeanMertz I'm also grateful at the reminder that I can use the IP address instead of localhost. 
@stuffmc True, it shouldn't, but sheesh - you'd think you paid for it.  It's a free plugin that works in 99.9% of cases and here you have a clear way around the one bug you've found until it gets fixed.
