### ISSUE TITLE
Behaviour of new tab/window

### ISSUE THREAD

**Issue by BadSensorData** [rs/SafariOmnibar#53]
The behaviour of cmd+L is an excellent addition to the project.  Would it be possible to extend this so that when a new window or tab is opened the cursor is already in the omnibar, with text high lighted?  

I am constantly typing url's and search terms into my start page because I forget to type cmd+L after typing cmd+T

Keep up the excellent work, and many thanks.

**Comment by kersk** [comment]
I came here to report this same focus bug since I had been running into this as well. While typing up repo steps I noticed the following: 
- The issue only occurs for me when the tab bar becomes visible while going from "zero" tabs to two tabs. Once the tab bar is already visible, new tabs correctly start with keyboard focus in the omnibar as expected.
- As a workaround, if you set the tab bar to be always visible, this issue does not occur. To do this, you need to first close all other tabs so that the tab bar auto-hides, then you are able to select View -> Show Tab Bar.

Thanks!

**Comment by BadSensorData** [comment]
Showing the tab bar didn't seem to have an effect form me.  However, it got me playing around with settings a bit. I found that changing my settings so that a new window or new tab opens with "empty page" rather than my home page, the cursor defaults to the empty address bar and my fingers expect it to.

**Comment by rs** [comment]
This is a Safari bug actually
